server:
  port: 8081
  servlet:
    context-path: /api
      # context-path: parte di path che si frappone automaticamente tra host ed endpoint
    # http://{hostname}:{port}/{context-path}/{uri}
    # http://localhost:8081/api/....
  compression:
    enabled: true
    min-response-size: 2KB

# SPRING BOOT + DATABASE + MAIL
spring:
  application:
    name: uniproj

  datasource:
    url: jdbc:${DB_VENDOR}://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
      show-sql: true
      format_sql: true
      open-in-view: false
      defer-datasource-initialization: true

  logging:
    level:
      org.springframework: info
      zteo.esercitazione.Universita: info
      org.hibernate.orm.jdbc.bind: trace

spring-doc:
  swagger-ui:
    enabled: true
    # http://localhost:8081/api/swagger-ui/index.html
    path: /swagger-ui/index.html
    tags-sorter: alpha
    display-request-duration: true